# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='report_freqs',
            field=models.CharField(default='weekly', max_length=50),
        ),
    ]
