# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='member_access_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
    ]
