# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180405_1938'),
        ('api', '0027_check_priority'),
    ]

    operations = [
    ]
