# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20180417_0739'),
        ('api', '0030_merge_20180417_0803'),
    ]

    operations = [
    ]
