# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20180417_0926'),
        ('api', '0027_auto_20180412_1226'),
    ]

    operations = [
    ]
